name: GitHub Actions Demo
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo & checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'maven'
      - name: Build
        run: ./mvnw package
      - name: Run JUnit
        run: ./mvnw test
      - name: Run Sonar Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=${{github.repository}}